spring.application.name=backend
# Server Port
server.port=${PORT:9040}
# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:${MYSQL_URL:jdbc:mysql://nozomi.proxy.rlwy.net:54103/railway}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD:oQLwlNmcuDTsTtnJjeIbBaqIkFRqYOvf}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Allow CORS for the React frontend
cors.allowed.origins=*
# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:shaikirshan78@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:hfhuyzmjofnadazi}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true